---
title: "Assignment 2"
# date: "2020-06-08"
# due_date: "2020-06-08"
# due_time: "11:59 PM"
# menu:
#   assignment:
#     parent: Assignments
#     weight: 2
type: docs
weight: 1
output:
  blogdown::html_page:
    toc: true
editor_options: 
  chunk_output_type: console
---

# To do yourself, due before 09-29-2020 class

- Install [swirl](https://swirlstats.com/students.html) R package, the [R Programming](https://github.com/swirldev/R_Programming_E) course, and run through it. Screenshot when the course is complete.
    - For statistical functions, install and run "Mathematical_Biostatistics_Boot_Camp", "Statistical_Inference", "Regression_Models" courses
    - Explore [other swirl courses](https://github.com/swirldev/swirl_courses)
    

# To submit on blackboard, due 09-29-2020, 5:00pm

1) Use the help functions or R documentation to look up a function that you think you will use in one of your courses this year. Provide (in words) a description of what the function is and does, the arguments that takes, and anything else that might be relevant about this function. Then, using a sample dataset in R (i.e., `mtcars`, `iris`, `ToothGrowth`), demonstrate (in code) the use of this function

2) Create two numeric, two character, and two logical objects/variables in R. Give them descriptive names. Provide code examples

3) Use some function that operates on the two numeric objects, another that operates on the two character objects, and another that operates on the two logical objects. 

4) Look up an R package that you think might be useful to you this year. Provide all code for installing it and loading it into your R workspace for use

5) Describe all ways how to find:
    - Path(s) where R packages are installed
    - Copy-paste selected output and describe your observations

6) What is unuwual about each of the following objects?

``` r
num_char     <- c(1, 2, 3, "a")
num_logical  <- c(1, 2, 3, TRUE)
char_logical <- c("a", "b", "c", TRUE)
tricky       <- c(1, 2, 3, "4")
```


- Submit your homework as a text or Word document. Name your file as "<last_name>_<first_name>_Hw02"