---
title: "Assignment 3: R base graphics, statistical functions"
date: "2020-09-29"
due_date: "2020-10-06"
due_time: "5:00 PM"
menu:
  assignment:
    parent: Assignments
    weight: 3
type: docs
weight: 1
output:
  blogdown::html_page:
    toc: false
editor_options: 
  chunk_output_type: console
---
  
# To do yourself, due before 10-02-2020 class

- Subscribe to [R-bloggers](https://www.r-bloggers.com/) mailing list or RSS feed

- Watch playlists/videos from [Brooke Anderson's channel](https://www.youtube.com/channel/UC73v_zCdNE2aZrFZsG22JBw/playlists), as well as her [R Programming for Research](https://geanders.github.io/RProgrammingForResearch/) course

- Install [swirl](https://swirlstats.com/students.html) R package
    - For statistical functions, install and run "Mathematical_Biostatistics_Boot_Camp", "Statistical_Inference", "Regression_Models" courses
    - Explore [other swirl courses](https://github.com/swirldev/swirl_courses)
    
- [Statistical functions](https://geanders.github.io/RProgrammingForResearch/exploring-data-3.html)

- [read.table, readr, Excel, SAS, SPSS, file/folder structure/paths](https://geanders.github.io/RProgrammingForResearch/entering-and-cleaning-data-1.html)

- Download or clone the [RGraphics](https://github.com/clayford/RGraphics) repository, and run through code in the [R_graphics_workshop.R](https://raw.githubusercontent.com/clayford/RGraphics/master/R_graphics_workshop.R) until `ggplot2` part (line 440)

# To submit on blackboard, due 10-06-2020, 5:00pm

1. Install package "babynames"  
  - How many values are in the `babynames` object?  
  - What their data types?  
  - Get an overview of `babynames`  
  - Plot the proportion of your name usage vs. year. Choose closest or random name, if your exact spelling is not available  

2. Load in the ToothGrowth dataset, which comes with R.  
  - Produce a boxplot of the tooth length variable, with x- and y-axis labels as well as a title.  
  - Change the graphics parameters to a window of one row and two columns of plots. Then, populate the first one with a scatterplot of dose on the x-axis and length on the y-axis, only using observations with a VC supplement type. Populate the second one with a scatterplot of dose on the x-axis and length on the y-axis, only using observations with an OJ supplement type. Provide informative axis labels. Use filled-in circles as the plotting character in the first plot, and filled-in triangles as the plotting character in the second plot.  
  - Fit a linear regression model of tooth length on the variables 'supp' and 'dose'. Change the graphics parameters back to just one plot, not several. Plot *only* the QQ-plot of residuals from this regression model, filled in with blue circles. 

3. Set a seed to ensure reproducibility. Then, generate $n=100$ random variables from a a $Exponential(\lambda=5)$ distribution. Plot the empirical CDF (cumulative distribution function) of this data with informative axes labels. Make a really long title - so long that you must use a special character to get the title to go on two lines.
